on:
  schedule:
    - cron: '35 12 9,22 * *'
  workflow_dispatch:

name: Cron continuous integration

permissions: {}

jobs:
  markdown-link-check:
    if: github.repository_owner == 'jdx'
    runs-on: ubuntu-24.04
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: umbrelladocs/action-linkspector@568ec8d29fa92b31fd9ea5381e155c51e922af83 # v1.5.5
        with:
          reporter: github-check
          filter_mode: "nofilter"
